# Spring Boot 配置
spring.application.name=dubbo-server

# Dubbo 配置
dubbo.application.name=dubbo-server
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.protocol.serialization=hessian2
dubbo.registry.address=nacos://192.168.11.12:8848