# Spring Boot 配置
spring.application.name=dubbo-client
server.port=8880

# Dubbo 配置
dubbo.application.name=dubbo-client
dubbo.protocol.serialization=hessian2
dubbo.registry.address=nacos://192.168.11.12:8848