# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: full_access_log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66ull_access_log.proto\x12\x06\x61ta.v1\"\xd0\x01\n\rFullAccessLog\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12/\n\x0f\x63onnection_info\x18\x02 \x01(\x0b\x32\x16.ata.v1.ConnectionInfo\x12 \n\x07request\x18\x03 \x01(\x0b\x32\x0f.ata.v1.Request\x12\"\n\x08response\x18\x04 \x01(\x0b\x32\x10.ata.v1.Response\x12\x0f\n\x07node_id\x18\x05 \x01(\t\x12#\n\tuser_info\x18\x06 \x01(\x0b\x32\x10.ata.v1.UserInfo\"\x98\x04\n\x0e\x43onnectionInfo\x12!\n\x19\x64ownstream_remote_address\x18\x01 \x01(\t\x12 \n\x18\x64ownstream_local_address\x18\x02 \x01(\t\x12(\n downstream_direct_remote_address\x18\x03 \x01(\t\x12\x15\n\rupstream_host\x18\x04 \x01(\t\x12\x1e\n\x16upstream_local_address\x18\x05 \x01(\t\x12\x1c\n\x14virtual_cluster_name\x18\x06 \x01(\t\x12\x12\n\nroute_name\x18\x07 \x01(\t\x12\x18\n\x10upstream_cluster\x18\x08 \x01(\t\x12\x1f\n\x17\x64ynamic_metadata_filter\x18\t \x01(\x0c\x12\x12\n\nstart_time\x18\n \x01(\x03\x12\x10\n\x08\x64uration\x18\x0b \x01(\x03\x12\x18\n\x10request_duration\x18\x0c \x01(\x03\x12\x1b\n\x13request_tx_duration\x18\r \x01(\x03\x12\x19\n\x11response_duration\x18\x0e \x01(\x03\x12\x1c\n\x14response_tx_duration\x18\x0f \x01(\x03\x12\x16\n\x0e\x62ytes_received\x18\x10 \x01(\x03\x12\x12\n\nbytes_sent\x18\x11 \x01(\x03\x12\x1c\n\x14listener_stat_prefix\x18\x12 \x01(\t\x12\x13\n\x0borigin_host\x18\x13 \x01(\t\"H\n\x07Request\x12\x16\n\x0eraw_start_line\x18\x01 \x01(\t\x12\x13\n\x0braw_headers\x18\x02 \x01(\t\x12\x10\n\x08raw_body\x18\x03 \x03(\x0c\"I\n\x08Response\x12\x16\n\x0eraw_start_line\x18\x01 \x01(\t\x12\x13\n\x0braw_headers\x18\x02 \x01(\t\x12\x10\n\x08raw_body\x18\x03 \x03(\x0c\"L\n\x08UserInfo\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\t\x12\x0f\n\x07rule_id\x18\x04 \x01(\tb\x06proto3')



_FULLACCESSLOG = DESCRIPTOR.message_types_by_name['FullAccessLog']
_CONNECTIONINFO = DESCRIPTOR.message_types_by_name['ConnectionInfo']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_USERINFO = DESCRIPTOR.message_types_by_name['UserInfo']
FullAccessLog = _reflection.GeneratedProtocolMessageType('FullAccessLog', (_message.Message,), {
  'DESCRIPTOR' : _FULLACCESSLOG,
  '__module__' : 'full_access_log_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.FullAccessLog)
  })
_sym_db.RegisterMessage(FullAccessLog)

ConnectionInfo = _reflection.GeneratedProtocolMessageType('ConnectionInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONINFO,
  '__module__' : 'full_access_log_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.ConnectionInfo)
  })
_sym_db.RegisterMessage(ConnectionInfo)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'full_access_log_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'full_access_log_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.Response)
  })
_sym_db.RegisterMessage(Response)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'full_access_log_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FULLACCESSLOG._serialized_start=34
  _FULLACCESSLOG._serialized_end=242
  _CONNECTIONINFO._serialized_start=245
  _CONNECTIONINFO._serialized_end=781
  _REQUEST._serialized_start=783
  _REQUEST._serialized_end=855
  _RESPONSE._serialized_start=857
  _RESPONSE._serialized_end=930
  _USERINFO._serialized_start=932
  _USERINFO._serialized_end=1008
# @@protoc_insertion_point(module_scope)
