# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import full_access_log_pb2 as full__access__log__pb2
import publish_pb2 as publish__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x06\x61ta.v1\x1a\x15\x66ull_access_log.proto\x1a\rpublish.proto\"\x9d\x01\n\x0bQueryResult\x12)\n\naccess_log\x18\x01 \x01(\x0b\x32\x15.ata.v1.FullAccessLog\x12+\n\rmatched_label\x18\x02 \x03(\x0b\x32\x14.ata.v1.MatchedLabel\x12\x15\n\rstorage_limit\x18\x03 \x01(\x08\x12\x1f\n\x05\x66iles\x18\x04 \x03(\x0b\x32\x10.ata.v1.FileInfo\"I\n\nQueryParam\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0cstorage_time\x18\x02 \x01(\t\x12\x11\n\twith_file\x18\x03 \x01(\t\";\n\x0f\x42\x61tchQueryParam\x12(\n\x0cquery_params\x18\x02 \x03(\x0b\x32\x12.ata.v1.QueryParam\"8\n\x10\x42\x61tchQueryResult\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.ata.v1.QueryResult\"g\n\x15\x42\x61tchHeaderQueryParam\x12\x12\n\nheader_key\x18\x01 \x01(\t\x12\x12\n\nis_request\x18\x02 \x01(\x08\x12&\n\nquery_list\x18\x03 \x03(\x0b\x32\x12.ata.v1.QueryParam\"=\n\x11HeaderQueryResult\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0cheader_value\x18\x02 \x01(\t\"D\n\x16\x42\x61tchHeaderQueryResult\x12*\n\x07results\x18\x01 \x03(\x0b\x32\x19.ata.v1.HeaderQueryResultb\x06proto3')



_QUERYRESULT = DESCRIPTOR.message_types_by_name['QueryResult']
_QUERYPARAM = DESCRIPTOR.message_types_by_name['QueryParam']
_BATCHQUERYPARAM = DESCRIPTOR.message_types_by_name['BatchQueryParam']
_BATCHQUERYRESULT = DESCRIPTOR.message_types_by_name['BatchQueryResult']
_BATCHHEADERQUERYPARAM = DESCRIPTOR.message_types_by_name['BatchHeaderQueryParam']
_HEADERQUERYRESULT = DESCRIPTOR.message_types_by_name['HeaderQueryResult']
_BATCHHEADERQUERYRESULT = DESCRIPTOR.message_types_by_name['BatchHeaderQueryResult']
QueryResult = _reflection.GeneratedProtocolMessageType('QueryResult', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESULT,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.QueryResult)
  })
_sym_db.RegisterMessage(QueryResult)

QueryParam = _reflection.GeneratedProtocolMessageType('QueryParam', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPARAM,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.QueryParam)
  })
_sym_db.RegisterMessage(QueryParam)

BatchQueryParam = _reflection.GeneratedProtocolMessageType('BatchQueryParam', (_message.Message,), {
  'DESCRIPTOR' : _BATCHQUERYPARAM,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.BatchQueryParam)
  })
_sym_db.RegisterMessage(BatchQueryParam)

BatchQueryResult = _reflection.GeneratedProtocolMessageType('BatchQueryResult', (_message.Message,), {
  'DESCRIPTOR' : _BATCHQUERYRESULT,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.BatchQueryResult)
  })
_sym_db.RegisterMessage(BatchQueryResult)

BatchHeaderQueryParam = _reflection.GeneratedProtocolMessageType('BatchHeaderQueryParam', (_message.Message,), {
  'DESCRIPTOR' : _BATCHHEADERQUERYPARAM,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.BatchHeaderQueryParam)
  })
_sym_db.RegisterMessage(BatchHeaderQueryParam)

HeaderQueryResult = _reflection.GeneratedProtocolMessageType('HeaderQueryResult', (_message.Message,), {
  'DESCRIPTOR' : _HEADERQUERYRESULT,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.HeaderQueryResult)
  })
_sym_db.RegisterMessage(HeaderQueryResult)

BatchHeaderQueryResult = _reflection.GeneratedProtocolMessageType('BatchHeaderQueryResult', (_message.Message,), {
  'DESCRIPTOR' : _BATCHHEADERQUERYRESULT,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:ata.v1.BatchHeaderQueryResult)
  })
_sym_db.RegisterMessage(BatchHeaderQueryResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYRESULT._serialized_start=62
  _QUERYRESULT._serialized_end=219
  _QUERYPARAM._serialized_start=221
  _QUERYPARAM._serialized_end=294
  _BATCHQUERYPARAM._serialized_start=296
  _BATCHQUERYPARAM._serialized_end=355
  _BATCHQUERYRESULT._serialized_start=357
  _BATCHQUERYRESULT._serialized_end=413
  _BATCHHEADERQUERYPARAM._serialized_start=415
  _BATCHHEADERQUERYPARAM._serialized_end=518
  _HEADERQUERYRESULT._serialized_start=520
  _HEADERQUERYRESULT._serialized_end=581
  _BATCHHEADERQUERYRESULT._serialized_start=583
  _BATCHHEADERQUERYRESULT._serialized_end=651
# @@protoc_insertion_point(module_scope)
